### ISSUE TITLE
"Add to Calendar" button functionality needed

### ISSUE THREAD

**Issue by hyperboy** [SU-SWS/stanford_events_importer#11]
It would be nice to be able to add an event from the Drupal events calendar to the user's personal calendar.  It might be possible to leverage the "Add to Calendar" functionality on events.stanford.edu.

Here's a jQueryUI implementation of the "Add to Calendar" button.
https://github.com/tardate/jquery.addtocalendar

**Comment by jbickar** [comment]
This actually looks to be a service provided by events.stanford.edu. At https://healthcaretech.stanford.edu, there's an "Add this to my calendar" link that points to https://events.stanford.edu/ical/download.php?id=33273. We could pull in the unique ID of the event and use computed field to construct the link (or ask Scott to include the iCal link in the XML feed).

**Comment by jbickar** [comment]
Scott will add this to XML feed

**Comment by stocker** [comment]
Hi John,

<eventID> is now in the XML feed.  You can construct the "Add to Calendar" URL as: http://events.stanford.edu/ical/download.php?id=<eventID>

If it helps for me to add another element to <Event> which contains that URL (e.g., <icalUrl>), let me know.

Scott
