### ISSUE TITLE
Change default date format so it's not in military time

### ISSUE THREAD

**Issue by meganem** [SU-SWS/stanford_events_importer#12]

**Comment by jbickar** [comment]
This is tricky because it defaults to the default Drupal "long" date format, and we can't assume end users will have other formats set up. I can try to export a date format, but I seem to remember that these were not fully Features exportable (maybe they are for D7 though).

**Comment by jbickar** [comment]
b60a712

**Comment by zchandler** [comment]
Strongarm

**Comment by jbickar** [comment]
That's such a good idea that I went back in time and committed a fix to this issue 13 minutes before your comment, using your suggested implementation :P
