### ISSUE TITLE
Field date timezone set to UTC

### ISSUE THREAD

**Issue by mksweet** [SU-SWS/stanford_events_importer#17]
The timezone handling for field_stanford_event_datetime is set to UTC.

This causes the date to be imported incorrectly, and therefore tokens to be generated incorrectly (tokens use the site's default timezone). There is a known feeds issue about this: http://drupal.org/node/722740.

It would make sense to set the timezone handling to Los Angeles since most Stanford sites will be in that timezone.

**Comment by mksweet** [comment]
Or set it to the the site's default timezone. This is what I did.

**Comment by mksweet** [comment]
Update: Setting the timezone to the site's default fixes the above issue of dates being incorrect, but causes times to come in 7 hours ahead.

**Comment by jbickar** [comment]
http://events.stanford.edu/events/372/37285/

**Comment by jbickar** [comment]
Not sure if present in 7.x-1.x

**Comment by jbickar** [comment]
At first blush, adding the "convert string to UNIX timestamp" Feeds Tamper plugin to the date start and end field mapping in the Feeds importer does the trick. This was when setting the date field to use the site's time zone.

Need to test with date field still set to UTC (for backwards compatibility) and test all-day events.
