### ISSUE TITLE
Remove menu settings?

### ISSUE THREAD

**Issue by cjwest** [SU-SWS/stanford_events_importer#18]
Since events generally don't end up as menu items, would it make sense to remove the ability to add an event to a menu item?

![screen shot 2013-10-16 at 3 48 39 pm](https://f.cloud.github.com/assets/284440/1347767/c794c4ae-36b5-11e3-9b8b-c60fa78a8e2d.png)

**Comment by sherakama** [comment]
This has been resolved in the latest.
