### ISSUE TITLE
7.x-2.x -> 7.x-3.x upgrade path

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/stanford_events_importer#35]
When upgrading from 7.x-2.x to 7.x-3.x, on a site with existing event and importer content, one of the hook_update_N() implementations fails with the following error:

FieldException: Cannot change an existing field's type. in field_update_field() (line 234 of /var/www/ds_vpge-dev/public_html/modules/field/field.crud.inc)

(I'm pretty sure it's 7300 that fails.) 

Specifically, I tried updating from 7.x-2.0-beta8 to 7.x-3.0-alpha6 on vpge-dev.

**Comment by jbickar** [comment]
@sherakama please take a look when you have some free time :)

**Comment by sherakama** [comment]
@jbickar, This should be resolved now in: 657f1ef06ecb12d2a11fa2321d705a66737dcd27
